import Head from "next/head";
import Container from "react-bootstrap/Container";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

function ParagraphWrapper({children, number}: {children: React.ReactNode, number: number}) {
  return (
    <div className="position-relative">
      <span className="badge bg-primary rounded-pill position-absolute end-100 me-0 mt-3">
        {number}
      </span>
      <div className="p-3">
      {children}

      </div>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>INVITATION FOR PRELIMINARY SCREENING PROCESS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="position-relative">
        <hr
          style={{
            display: "block",
            height: "1px",
            top: "120px",
            width: "100vw",
            border: "0",
            borderTop: "15px solid #1a4f9a",
            margin: "1em 0",
            padding: "0",
            opacity: 1,
          }}
          className="position-absolute"
        />
        <hr
          style={{
            display: "block",
            height: "1px",
            top: "135px",
            width: "100vw",
            border: "0",
            borderTop: "15px solid #43b54a !important",
            margin: "1em 0",
            padding: "0",
            opacity: 1,
          }}
          className="position-absolute"
        />
      </div>
      <Container as="main" className="py-4 px-3 mx-auto">
        <Header />
        <div className="container text-left">
          <div className="row">
            <div className="col">
              <h3>Notice of Preliminary Screening Process</h3>
              <ParagraphWrapper number={1}>
              <p>
                  The Government of the Republic of Indonesia, represented by
                  its Ministry of Finance, has received a loan from the Japan
                  International Cooperation Agency (JICA) towards the cost of
                  Eighty-Seven Billion Nine Hundred Eighteen Million Japanese
                  Yen (JPY87,918,000,000) and intends to apply part of the
                  proceeds towards payments under the Contract Package CP205:
                  Railway Systems and Track Work.
                </p>
              </ParagraphWrapper>
              <ParagraphWrapper number={2}>
              <p>
                PT Mass Rapid Transit Jakarta (Perseroda) now intends to conduct
                a preliminary screening process for firms interested in the
                CP205 Contract Package: Railway Systems and Track Work for
                Construction of Jakarta Mass Rapid Transit Project (Phase 2)
                (I), as below:
              </p>
              <p>
                Railway Systems for Bundaran HI to Kota, including Substation
                System, Overhead Contact System, Power Distribution System,
                Signaling System, Telecommunication System, Facility SCADA,
                Platform Screen Doors, modification to the existing equipment
                installed in the existing OCC at Lebak Bulus Depot (Phase 1) and
                the existing stations/train sets (Phase 1), and Track Work,
                including associated systems/subsystems for 3,800 m (approx.) of
                twin tube tunnels, 2,050 m (approx.) of cut and cover tunnel
                structure, seven underground stations, and 1 receiving
                sub-station and 2 traction sub-stations.
              </p>
              </ParagraphWrapper>
            </div>
            <div className="col">
            
              <p>
                Contract Name: Contract Package CP205: Railway Systems and Track
                Work
              </p>
              <ParagraphWrapper number={3}>
                <p>
                This procurement is for the re-bidding process following the
                failure of the bid process for Contract Package CP 205: Railway
                Systems and Track Work (Bundaran HI – Kota) that started in
                2022.
              </p>
              </ParagraphWrapper>
              <ParagraphWrapper number={4}>
              <p>
                The Bidding will be conducted through procedures following the
                applicable guidelines for Procurement under Japanese ODA Loans
                published in April 2012. The new CP205 re-bidding process is
                based on Limited Bidding with Bilateral Tied, where the prime
                contractor shall be Indonesian, Japanese, or JV
                IndonesianJapanese, and it shall only be open to the
                pre-screened companies and/or Joint Ventures
              </p>
              </ParagraphWrapper>
              <ParagraphWrapper number={5}>
              <p>
                The preliminary screening process will be conducted before the
                Invitation for Bids, from 1st September 2023 through 7th
                September 2023. Interested applicants must submit the Letter of
                Intent, associated forms and supporting documents under
                Attachment-5 via email anytime from 1st September through 7th
                September 2023. Invitation for Bids to the pre-screened
                companies is expected to be issued on 8th September 2023, and
                the pre-screened applicants will be invited to collect the
                bidding documents between 11th September 2023 and 13th September
                2023. The deadline for the bid submission is 30th November 2023
                at 5:00 pm Jakarta time.
              </p>
              </ParagraphWrapper>
              
              
            </div>
            <div className="col">
              <p>JICA Loan No.: IP-578, IP-585 and subsequent JICA Loans</p>
              <p>Preliminary Screening Process Requirements</p>
              <ParagraphWrapper number={6}>
              <p>
                Applicants must thoroughly review the provided Compliance
                Requirements for Eligibility and Qualification Criteria
                (Attachment-2: Compliance Requirements for Eligibility and
                Qualification Criteria) and ensure a clear understanding of the
                document.
              </p>
              </ParagraphWrapper>
              
              <p>
                To express their intent to participate in the procurement of
                Contract Package CP205, applicants shall submit:
              </p>
              <p className="ms-4">
                a) Letter of Intent (LOI) for Bidding Preparation
                (Attachment-3); along with
              </p>
              <p className="ms-4">
                b) Forms ELI-1, ELI-2, FIN-2, EXP-1, and EXP-2(a) (Attachment-5)
                and associated supporting documents in accordance with
                Sufficiency of Compliance Requirements for Eligibility and
                Qualification Criteria Checklist (Attachment-4).
              </p>
              <p>
                The format of the LOI and the required documents can be obtained
                from the Employer’s official website.
              </p>
              <p>
                For Joint Venture (JV) applicants, the submission should include
                either the JV agreement or a Letter of Intent for making a JV
                indicating the plan to enter into such an agreement. The JV
                agreement (or the Letter of Intent) must distinctly state the
                name of the leading partner company and the equity distribution
                among JV members (if applicable).
              </p>
            </div>
          </div>
        </div>

        <hr className="col-1 my-5 mx-0" />
      </Container>
      <Footer />
    </>
  );
}
